9. Выполнение домашней работы №5
UBaHbI4/PopularLibraryCourse pull request #9
Opened 2021-08-16 14:08 UTC by UBaHbI4

- Добавлен экран для детализации информации выбранного репозитория.
- По клику на пользователя открывается список его репозиториев, по которым можно кликнуть для получения более детальной информации.
- Рефакторинг кода

2021-08-19 12:30 UTC, PeterBukhal-sovcombank requested changes
Есть критические замечания. Пока не принимаю.

2021-08-19 12:30 UTC, PeterBukhal-sovcombank commented on app/src/main/java/softing/ubah4ukdev/popularlibrary/domain/api/GitHubApi.kt
> +    fun repoList(@Path("login") login: String): Single<List<GitHubRepository>>
Хорошей практикой наименования методов является использование глагола в начале `fetchUser()`,  `openFile()` и тд. Название методов совершенно не документируют код и не облегчают его чтение. Не нужно злоупотреблять сокращениями. https://kotlinlang.org/docs/coding-conventions.html#naming-rules.

2021-08-19 12:30 UTC, PeterBukhal-sovcombank commented on app/src/main/java/softing/ubah4ukdev/popularlibrary/domain/repository/MockUsersRepositoryImpl.kt
> +        TODO("Not yet implemented")
:-1: Как я понимаю репозитории оно не возвращает?))

2021-08-19 12:30 UTC, PeterBukhal-sovcombank commented on app/src/main/java/softing/ubah4ukdev/popularlibrary/presenter/repodetail/RepositoryFragment.kt
> +        requireActivity().title = repo?.name
:-1: `View` не должно ничего запрашивать у `Presenter`, но только `Presenter` сообщает представлению `View`, что делать, то что сделано у тебя это прямое и **грубое нарушение** `MVP`.

2021-08-19 18:27 UTC, UBaHbI4 commented on app/src/main/java/softing/ubah4ukdev/popularlibrary/domain/api/GitHubApi.kt
> +    fun repoList(@Path("login") login: String): Single<List<GitHubRepository>>
В домашней работе №7 пересмотрел все файлы, постарался везде дать адекватные название.

2021-08-19 18:28 UTC, UBaHbI4 commented on app/src/main/java/softing/ubah4ukdev/popularlibrary/domain/repository/MockUsersRepositoryImpl.kt
> +        TODO("Not yet implemented")
> 👎 Как я понимаю репозитории оно не возвращает?))

Теперь возвращает :) можно было в принципе просто удалить замоканный репозиторий?

2021-08-19 18:28 UTC, UBaHbI4 commented on app/src/main/java/softing/ubah4ukdev/popularlibrary/presenter/repodetail/RepositoryFragment.kt
> +        requireActivity().title = repo?.name
> 👎 `View` не должно ничего запрашивать у `Presenter`, но только `Presenter` сообщает представлению `View`, что делать, то что сделано у тебя это прямое и **грубое нарушение** `MVP`.

Исправил.

2021-08-20 06:46 UTC, PeterBukhal-sovcombank approved these changes
Отлично, задание выполнено, замечаний нет.

2021-08-20 07:02 UTC, merged